### ISSUE TITLE
Wiped out all my settings on install - even reverted me to .net 3.5

### ISSUE THREAD

**Issue by MostHated** [jedybg/yaSingleton#1]
Hello,
    I am not sure what is up with this, but the moment I imported the asset from the store, I started to get compile issues, so I restarted Unity and then now all of my settings were wiped out. All my tag setup, controls for Rewired, it even reverted my project to .net 3.5. It was quite a hassle to get everything back where it was supposed to be.

It was a fresh download about 30 minutes ago, Unity 2017.4.2f2 .net 4.6 (at least it was).

---- Edit, what is even more, I found out, it didn't wipe out ALL the settings, just build settings, input settings, nav mesh areas, project settings, graphics, and tags. 

Thanks,

**Comment by heyJordanParker** [comment]
Heya,

I'm sorry for the inconvenience!

I've found that the issue is that I've published the asset in the Complete Projects/Tools category which on a second read of the guidelines seems to be the problem. Anything in the "Complete Projects" category or subcategories will have the original project settings included.

I've updated the category to avoid that major hassle for future users (but it will take a few days for it to get reviewed and updated in the asset store).

I will update this issue as soon as the updated package is approved and I manually validate it.

Thank you for reporting - you've potentially saved a lot of time for everyone who downloads this!

**Comment by heyJordanParker** [comment]
This is resolved now. The asset store version now contains commit e967a183a8d17548f584190c302e2e1f754ea462 and I switched the category. Importing the package now, just imports the files themselves and all settings have been deleted.
